name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to remote server
        run: |
          rsync -avz --exclude='.git*' --exclude='node_modules' --exclude='__pycache__' ./ ${{ secrets.REMOTE_USER }}@74.208.69.50:/var/repository/github/annotyze

      - name: Run deployment script on remote server
        run: |
          ssh ${{ secrets.REMOTE_USER }}@74.208.69.50 'cd /var/repository/github/annotyze && ./dev.sh rebuild'
